"""empty message

Revision ID: 471bdfdd98fc
Revises: 17cdb6e14587
Create Date: 2024-11-29 13:40:15.167397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471bdfdd98fc'
down_revision = '17cdb6e14587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['doc_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name')
        batch_op.drop_column('doc_id')

    # ### end Alembic commands ###
